theme: jekyll-theme-dinky
name: title remove
title: false
title: Khang Vo Huynh
description: Picture taken by Huy V. Huynh
logo: https://github.com/HVKHCM/HVKHCM.github.io/blob/main/Profile-picture.jpg?raw=true
show_downloads: false
