theme: jekyll-theme-minimal
name: title remove
title: false
title: Khang Vo Huynh
description: Picture taken by younger brother
logo: https://github.com/HVKHCM/HVKHCM.github.io/blob/main/Profile-picture.jpg?raw=true
show_downloads: false
